# - name: Install prerequisites
#   apt:
#     name:
#       - ca-certificates
#       - curl
#       - gnupg
#       - lsb-release
#     update_cache: yes

# - name: Add Docker GPG key
#   ansible.builtin.apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

# - name: Add Docker repository
#   ansible.builtin.apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
#     state: present

# - name: Install Docker Engine
  # apt:
    # name:
      # - docker-ce
      # - docker-ce-cli
      # - containerd.io
    # state: present
    # update_cache: yes

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started
